import Link from 'next/link';
import {rivers} from '@/data/rivers';
import {sources} from '@/data/sources';
import {media} from '@/data/media';
import {EvidenceList} from '@/components/evidence';
import MediaFigure from '@/components/media-figure';
import {appHref} from '@/lib/public-path';
export const metadata={title:'项目、研究方法与证据档案'};
export default function About(){return <main id="main-content"><header className="page-intro"><p className="kicker">ABOUT THE ARCHIVE / 方法与边界</p><h1>让每份档案，都能回到证据。</h1><p>河流生命档案——流域治理交互式案例知识平台。以河流为索引，将空间、时间、主体、制度、事件和数字治理过程重新组织，支持自主阅读与教学研讨。</p></header><div className="content-body"><section className="about-grid" id="method"><div><h2>研究什么</h2><p>作品辅助案例《让河流说话，让治理回应——重庆“巴渝治水”从跨界协同到智能智治》，用于清华大学2026年中国智能社会治理公共政策案例分析大赛。</p><p>研究重点是自然流域与行政责任的差异、数字技术如何改变协同，以及反馈如何可能进入规划与资源配置。</p></div><div><h2>如何收录</h2><p>优先政府文件和官方公开报道，依据明确事件与制度机制组织档案。资料稀缺时降低表述精度，保留缺口，不补造时间、浓度、位置或成效。</p><p>本轮新增资料核验于2026年9月14日；原三河档案核验记录保留。河长制、工程治理和数字技术相互叠加，不构成简单替代关系。</p></div></section><div className="method-legend">{[['A','官方确认事实','有政府文件或官方报道支持；保留日期和统计口径。'],['B','研究团队整理','将不同来源编目、关联、归纳为角色和环节。'],['C','可视化示意','节点、连线和动画用于解释，不表示精确测量。'],['D','研究分析','机制解释与未来设想，区别于已实现的事实。']].map(([id,title,text])=><div key={id}><p className="kicker">{id}</p><h3>{title}</h3><p>{text}</p></div>)}</div><section className="detail-section" id="completeness"><h2>收录完整度</h2><p>“专题档案”有多阶段或具体事件证据；“基础档案”有可靠治理内容，但部分事件或数字环节仍待补。完整度是本站编辑状态，不是治理绩效评价。</p><div className="table-scroll"><table className="completeness-table"><thead><tr><th>档案</th><th>状态</th><th>已覆盖</th><th>尚缺</th></tr></thead><tbody>{rivers.map(r=><tr key={r.id}><td><Link href={'/rivers/'+r.id}>{r.name} ↗</Link></td><td>{r.status}{r.type==='region'?' / 区域':''}</td><td>{r.stage}；{r.eventIds.length}个历史/事件节点</td><td>{r.gaps.join('；')}</td></tr>)}</tbody></table></div></section><section className="detail-section" id="spatial"><h2>地图是真实边界，节点是区域示意。</h2><p>沿用DataV公开GeoJSON：重庆区县、四川地市、达州区县边界。原下载日期为2026-09-05；不作为现行行政区划、测绘或权属依据。高新区、万盛、双桥等管理区域通过文字区分。</p><p>未取得真实河道、断面、污染源的可靠公开经纬度。全部案例节点是编辑选取的区县级示意位置，连线是治理关系。现有底图未取得明确再分发许可声明，正式参赛应进一步确认地图使用与授权条件。</p><Link href={sources.find(s=>s.id==='S13')!.url} target="_blank" rel="noreferrer">打开原始边界数据 ↗</Link></section><section className="detail-section" id="media"><h2>真实影像与使用条件</h2><p>收录两张实景照片与一张地理影像，均有开放许可记录。仅用于对应重庆城市或三峡库区背景，不冒充其他支流现场。各河政府报道照片保留原文入口，不把“公开可见”等同于“可自由转载”。</p><div className="media-library">{media.map(m=><div key={m.id}><MediaFigure id={m.id}/><p className="note-line">{m.scope}<br/>{m.changes}</p></div>)}</div><p>照片来源、caption、credit、originalUrl、许可、拍摄或数据日期和修改情况均独立记录。网络受限时显示文字与原始档案入口，主体阅读不依赖影像服务。</p></section><section className="detail-section" id="evidence"><h2>资料来源总索引</h2><p>展开条目查看发布机构、时间和原始链接。原网站内容及可达性由其维护。</p><EvidenceList/><div className="related-links"><a href={appHref('/data/archive.json')} download>下载完整档案编目 JSON ↓</a><Link href="/rivers">继续探索河流 →</Link></div></section></div></main>}
