'use client';
import {useEffect,useState,useId} from 'react';
import {rivers} from '@/data/rivers';
import {publicPath} from '@/lib/public-path';
type Feature={properties:{name:string};geometry:{type:string;coordinates:number[][][]|number[][][][]}};
const project=(p:number[])=>[(p[0]-104.8)*127,560-(p[1]-28)*130];
function geoPath(f:Feature){const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates as number[][][]]:f.geometry.coordinates as number[][][][];return polys.map(poly=>poly.map(ring=>ring.map((p,i)=>(i?'L':'M')+project(p).map(x=>x.toFixed(1)).join(',')).join(' ')+'Z').join(' ')).join(' ')}
const labelOffsets:Record<string,number[]>={tongbo:[20,15],xinsheng:[22,-22],longxi:[20,24],xiaoan:[-68,-18],liangtan:[18,24],linjiang:[-60,30],daqingliu:[-12,-25],puhe:[22,28],longhe:[22,20],sanxia:[-100,-20]};
export default function ArchiveMap({selected,onSelect,compact=false,visibleIds}:{selected:string;onSelect:(id:string)=>void;compact?:boolean;visibleIds?:string[]}){
 const [features,setFeatures]=useState<Feature[]>([]),[error,setError]=useState(false),[zoom,setZoom]=useState(1);const grid=useId();
 useEffect(()=>{let active=true;Promise.all(['/data/chongqing.geojson','/data/sichuan.geojson','/data/dazhou.geojson'].map(async u=>{const r=await fetch(publicPath(u));if(!r.ok)throw Error('map');return r.json() as Promise<{features:Feature[]}>})).then(([cq,sc,dz])=>{if(active)setFeatures([...sc.features.filter((f:Feature)=>['广安市','南充市','遂宁市','资阳市','内江市','泸州市'].includes(f.properties.name)),...dz.features,...cq.features])}).catch(()=>{if(active)setError(true)});return()=>{active=false}},[]);
 const river=rivers.find(c=>c.id===selected);const shown=rivers.filter(r=>!visibleIds||visibleIds.includes(r.id));
 return <div className={'geo-map atlas-map '+(compact?'compact':'')}><div className="map-top"><span>川渝流域治理地图</span><span>公开行政底图 / 案例区域示意</span></div>{error?<div className="map-fallback">地图文件未能加载。请使用旁边的档案列表继续探索。</div>:<svg viewBox="0 0 760 580" aria-label="重庆与川东行政边界，河流档案节点均为区域示意" role="group"><defs><pattern id={grid} width="38" height="38" patternUnits="userSpaceOnUse"><path d="M38 0H0V38" fill="none" stroke="#bccbd0" strokeWidth=".45"/></pattern></defs><rect width="760" height="580" fill={`url(#${grid})`}/><g transform={`translate(${380*(1-zoom)} ${290*(1-zoom)}) scale(${zoom})`}>{features.map((f,i)=><path key={i} d={geoPath(f)} className={river?.regionNames.includes(f.properties.name)?'region active-region':'region'}><title>{f.properties.name+' · 公开边界数据'}</title></path>)}<text x="112" y="150" className="province-label">四川</text><text x="565" y="220" className="province-label">重庆</text>{shown.map(c=>{const p=project(c.anchor),d=labelOffsets[c.id]||[15,-20];return <g key={c.id} role="button" tabIndex={0} aria-pressed={selected===c.id} aria-label={`预览${c.name}，区域示意位置`} onClick={()=>onSelect(c.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(c.id)}}} className={'map-pin '+(selected===c.id?'chosen':'')}><title>{c.name+' · '+c.regions}</title><rect x={Math.min(p[0]-15,p[0]+d[0]-8)} y={Math.min(p[1]-15,p[1]+d[1]-18)} width={Math.abs(d[0])+95} height={Math.abs(d[1])+32} fill="transparent" pointerEvents="all"/><circle cx={p[0]} cy={p[1]} r="14" className="pin-halo"/><circle cx={p[0]} cy={p[1]} r="5" className="pin-core"/><path d={`M${p[0]},${p[1]}L${p[0]+d[0]},${p[1]+d[1]-5}`} className="pin-line"/><text x={p[0]+d[0]} y={p[1]+d[1]} className="pin-label">{c.name.replace('（任市河）','')}</text></g>})}</g><text x="713" y="45" className="district-label">N ↑</text></svg>}<div className="map-controls"><button aria-label="放大地图" onClick={()=>setZoom(z=>Math.min(1.75,z+.25))} disabled={zoom>=1.75}>＋</button><button aria-label="缩小地图" onClick={()=>setZoom(z=>Math.max(1,z-.25))} disabled={zoom<=1}>−</button><button aria-label="重置地图" onClick={()=>setZoom(1)}>↺</button></div><div className="map-bottom"><span><i/> 选中案例涉及行政区</span><span>节点不是河道、监测站或污染源坐标</span></div></div>
}


