'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {riverForCase,archiveSourceForAgent} from '@/data/agent-links';
import {appHref} from '@/lib/public-path';
import {requestAnalysis,type AgentResult,type AgentEvidence} from '@/lib/agent-api';

const examples=[
 ['跨省异常 · 信息不足','某跨省河流水质异常，污染源未知，上下游信息不同步，应如何组织治理？'],
 ['跨区长期治理 · 机制建设','一条跨区河流长期水质反复，多个区县分别治理但效果不稳定，应建立什么协同机制？'],
 ['异常线索 · 部门协同','监测系统发现河流水质异常，但生态环境、水利和属地政府数据不同步，应如何组织响应？']
];
const metricNames:Record<string,string>={speed:'响应效率',affordability:'资源可承受性',control:'风险控制',sustainability:'长期持续性'};
function Items({values}:{values:string[]}){return <ul>{values.map((v,i)=><li key={i}>{v}</li>)}</ul>;}
function Evidence({values}:{values:AgentEvidence[]}){return <div className="agent-evidence">{values.map((e,i)=><p key={i}>{e.claim}<br/><small>定位：{e.locator} · <a href={'#agent-source-'+e.sourceId}>[{e.sourceId}] 查看来源</a></small></p>)}</div>;}
function safeLink(value:string){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:undefined;}catch{return undefined;}}

export default function AssistantWorkbench({rivers}:{rivers:{id:string;name:string}[]}){
 const [description,setDescription]=useState(''),[useLLM,setUseLLM]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<AgentResult|null>(null),[context,setContext]=useState<string|null>(null);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('river');if(rivers.some(r=>r.id===id))setContext(id);},[rivers]);
 const river=rivers.find(r=>r.id===context);
 async function submit(){if(busy)return;setBusy(true);setError('');setResult(null);try{setResult(await requestAnalysis(description,useLLM));}catch(e){setError(e instanceof Error&&e.name==='TimeoutError'?'请求等待超时，请稍后重试。':e instanceof TypeError?'无法连接治理助手API，请确认后端已启动、服务地址及CORS配置正确。':e instanceof Error?e.message:'分析暂不可用。');}finally{setBusy(false);}}
 const winner=result?.plans.find(p=>p.id===result.recommendation.plan);
 return <main id="main-content" className="agent-workbench">
  <header className="agent-cover"><p className="kicker">ANALYSE GOVERNANCE / 从档案到行动</p><h1>流域治理助手</h1><p className="lead">从案例中学习，在规则约束下分析治理情景</p><p>以真实案例为参照，以制度与职责为边界。把一个治理问题，拆解为可讨论、可比较、可追溯的行动选项。</p><div className="agent-method"><span>案例知识</span><b>→</b><span>治理规则</span><b>→</b><span>辅助分析</span><b>→</b><span>证据追溯</span></div></header>
  <section className="agent-input" aria-label="输入治理情景"><div><p className="kicker">01 / 输入治理情景</p><h2>这一次，需要协调什么？</h2><p className="note-line">描述当前问题或假设情景。未明确的风险保留为未知，不据此认定事件级别或污染责任。</p>{river&&<aside className="agent-context">你从 <Link href={'/rivers/'+river.id}>{river.name}档案</Link> 来到这里。该档案仅作为阅读背景，不会自动变成本次发生的事件。请自行描述新的或假设的情景。</aside>}</div>
   <form onSubmit={e=>{e.preventDefault();void submit();}}><label htmlFor="agent-description">治理问题 / 情景描述</label><textarea id="agent-description" required maxLength={8000} disabled={busy} value={description} onChange={e=>setDescription(e.target.value)} placeholder="描述你面对的流域治理问题，例如：某跨省河流水质异常，污染源未知，上下游信息不同步……"/><div className="agent-examples">{examples.map(([name,text])=><button type="button" key={name} disabled={busy} onClick={()=>setDescription(text)}>{name} ↗</button>)}</div><div className="agent-actions"><label><input type="checkbox" checked={useLLM} disabled={busy} onChange={e=>setUseLLM(e.target.checked)}/> 启用大模型补充解读</label><button className="ink-button" disabled={busy||!description.trim()}>{busy?'正在分析…':'开始治理分析 →'}</button></div><small>勾选后，情景与命中证据由后端发送给已配置模型；浏览器不接触模型密钥。</small></form>
  </section>
  {busy&&<section className="agent-state" role="status"><strong>正在检索案例、比较规则方案并等待辅助分析。</strong><p>真实模型可能需要一至三分钟；没有模型时，本地知识检索和规则推演仍可使用。</p></section>}
  {error&&<p className="agent-error" role="alert">{error}</p>}
  {result&&<div className="agent-results">
   <section><p className="kicker">02 / 情景识别与规则判断</p><h2>先理解问题，再组织行动</h2><p className="agent-query">{result.query}</p><div className="tag-line">{result.classification.tags.map(t=><span key={t}>{t} · 待核实</span>)}</div><p className="note-line">{result.classification.note}</p><div className="agent-recommend"><div><p className="kicker">规则引擎推荐：方案{result.recommendation.plan}</p><h3>{winner?.name}</h3><strong>{result.recommendation.conditional?'条件性推荐':'辅助推荐'} / 需有权人员核实</strong></div><div><p>{result.recommendation.reason}</p><p>{result.recommendation.sequence}</p><a href="#agent-policies">查看制度依据与适用限制 ↓</a></div></div><details><summary>待补充信息与核实任务</summary><Items values={result.classification.issues}/></details></section>
   <section><p className="kicker">03 / 相似案例</p><h2>从哪些历史经验中借鉴？</h2><p className="note-line">相关性来自现有检索，不是治理成功概率；类比不代表相同效果。</p><div className="agent-grid">{result.cases.map(c=>{const riverId=riverForCase(c.caseId);return <article key={c.caseId}><small>{c.caseId} / 检索相关性 {c.score.toFixed(3)}</small><h3>{c.name}</h3><h4>匹配理由</h4><Items values={c.reasons.filter(r=>!r.startsWith('文本特征：'))}/><h4>可借鉴经验 · 类比</h4><Items values={c.lessons}/><details><summary>迁移边界与历史证据</summary><Items values={c.boundaries}/><Evidence values={c.evidence}/></details>{riverId?<Link className="below-link" href={'/rivers/'+riverId}>查看河流档案 →</Link>:<p className="note-line">当前网站尚无对应河流档案，保留原案例证据。</p>}</article>;})}</div></section>
   <section><p className="kicker">04 / 主体与治理机制</p><h2>谁负责，如何协同？</h2><div className="agent-actors">{result.actors.map(a=><details key={a.name}><summary><strong>{a.name}</strong><span>{a.responsibility}</span></summary><p>权限边界：{a.authority}</p><p>协同：{a.coordination}</p><p>行动：{a.action}</p><p>制度依据：{a.basis.map(id=><a key={id} href={'#agent-policy-'+id}> {id} </a>)}</p></details>)}</div><div className="agent-grid">{result.mechanisms.map(m=><article key={m.id}><small>{m.id} / 类比机制</small><h3>{m.name}</h3><Items values={m.conditions}/><ol className="agent-flow">{m.steps.map(s=><li key={s}>{s}</li>)}</ol><details><summary>优势、风险与政策关联</summary><Items values={m.advantages}/><Items values={m.risks}/>{m.relatedPolicies.map(id=><a key={id} href={'#agent-policy-'+id}> {id} </a>)}</details></article>)}</div></section>
   <section><p className="kicker">05 / 方案比较</p><h2>在行动速度与长期协同之间权衡</h2><p className="note-line">评分为机制模拟和教学启发式，不代表真实环境治理结果。硬约束优先于分数。</p><div className="agent-grid">{result.plans.map(p=><article key={p.id} className={p.id===winner?.id?'agent-selected':''}><small>方案 {p.id}{p.id===winner?.id?' / 规则推荐':''}</small><h3>{p.name}</h3><p>{p.benefit}</p><div className="agent-bars">{Object.entries(p.metrics).map(([key,value])=><label key={key}><span>{metricNames[key]||key}</span><meter min={0} max={5} value={value}/><b>{value}/5</b></label>)}</div><p>加权分 {p.score} · {p.eligible?'可作为独立首选':'当前不宜独立首选'}</p><details><summary>行动步骤、成本与风险</summary><p>{p.cost}</p><p>{p.risk}</p><Items values={p.exclusions}/><ol>{p.steps.map((s,i)=><li key={i}><strong>{s.owner}</strong><p>{s.action}</p><small>交付物：{s.deliverable}</small></li>)}</ol></details></article>)}</div></section>
   <section><p className="kicker">06 / 大模型补充解读</p><h2>在证据约束下，进一步解释</h2><p className="agent-notice">{result.llm.note}</p>{result.llm.status==='success'&&<><div className="agent-model"><h3>补充分析</h3><p>{result.llm.analysis}</p><h3>辅助建议</h3><p>{result.llm.advice}</p></div><p>模型引用来源：{result.llm.sourceIds.map(id=><a key={id} href={'#agent-source-'+id}> [{id}] </a>)}</p><p className="note-line">已校验JSON结构及来源ID存在性，尚未验证逐句事实蕴含；本地规则推荐保持独立。</p></>}</section>
   <section id="agent-policies"><p className="kicker">07 / 制度与证据</p><h2>每项建议，都能回到依据</h2>{result.policies.map(p=><details id={'agent-policy-'+p.id} key={p.id}><summary>{p.id} / {p.name}</summary><Items values={p.requirements}/><h4>适用限制</h4><Items values={p.boundaries}/><Evidence values={p.evidence}/></details>)}<div className="agent-grid agent-sources">{result.sources.map(s=>{const archiveId=archiveSourceForAgent(s.id);return <article id={'agent-source-'+s.id} key={s.id}><small>AGENT / {s.id}{result.llm.sourceIds.includes(s.id)?' · 模型引用':''}</small><h3>{s.title}</h3><p>{s.publisher}<br/>{s.date||'日期未注明'}</p>{safeLink(s.url)&&<a href={safeLink(s.url)} target="_blank" rel="noopener noreferrer">查看原始来源 ↗</a>}{archiveId&&<p><a href={appHref('/about')+'#source-'+archiveId}>档案馆同源资料 {archiveId} →</a></p>}</article>;})}</div><details><summary>规则风险与审计信息</summary><Items values={result.risks}/><p>{result.audit.scoreNote}</p><p>知识版本：{result.audit.knowledgeVersion}</p><p className="agent-hash">SHA-256：{result.audit.knowledgeHash}</p></details></section>
  </div>}
  <aside className="agent-boundary">本工作台用于治理研究与辅助讨论，不提供污染预测，不替代官方监测、调查取证或有权机关决策。<Link href="/about#method">了解研究方法 →</Link></aside>
 </main>;
}
